INSERT INTO GENRES (GENRE_NAME) VALUES ('Комедия');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Драма');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Триллер');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Документальный');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Боевик');
INSERT INTO MPA (MPA) VALUES ('G');
INSERT INTO MPA (MPA) VALUES ('PG');
INSERT INTO MPA (MPA) VALUES ('PG-13');
INSERT INTO MPA (MPA) VALUES ('R');
INSERT INTO MPA (MPA) VALUES ('NC-17');

